
# Author:
#   Yuanqing Wu, KAUST, Saudi Arabia
#
# History:
#   2015-2-9 by Yuanqing Wu
#
# Support:
#   wuyuanq@gmail.com

PROG = CompositionalFlow_fortran_hpc_3D
defaults: ${PROG}

#FCC = gfortran
FCC = mpif90

#FCFLAGS = -O3 -fdefault-real-8 -g
#FCFLAGS = -O3 -g -traceback
#FCFLAGS = -O3 -fbounds-check
FCFLAGS = -O3 -g

FLASHTYPE = SPARSE
#FLASHTYPE =

ifeq ($(FLASHTYPE), SPARSE)
FLASHFLAGS = -DSPARSE
else
FLASHFLAGS = 
endif

VPATH = ../../FlashCalculation

ifeq ($(FLASHTYPE), SPARSE)
vpath RST_flashcalculation_fullgrid.F90 ../Fortran
endif

ifeq ($(FLASHTYPE), SPARSE)
FLASHSRCS = RST_globalFlashData.F90
else
FLASHSRCS = RST_globalFlashData.F90 RST_mathlib.F90 RST_PREOS.F90 RST_comprefac.F90 \
RST_fugacitycoef.F90 RST_stability.F90 RST_pmv.F90 RST_flashcalculation.F90
endif

ifeq ($(FLASHTYPE), SPARSE)
FSRCS = RST_globalData.F90 RST_model_3D.F90 RST_writeFile.F90 RST_genPlotfileMatlab.F90 RST_viscosity.F90 \
RST_flashcalculation_fullgrid.F90 RST_compositionalTwoPhaseFlow.F90 RST_compositionalTwoPhaseFlowDriver.F90 \
RST_proceAlloc.F90 infile_RSTi_compositionalTwoPhaseFlow.F90
else
FSRCS = RST_globalData.F90 RST_model_3D.F90 RST_writeFile.F90 RST_genPlotfileMatlab.F90 RST_viscosity.F90 \
RST_compositionalTwoPhaseFlow.F90 RST_compositionalTwoPhaseFlowDriver.F90 \
RST_proceAlloc.F90 infile_RSTi_compositionalTwoPhaseFlow.F90
endif
      
%.o: %.F90
	$(FCC) -c $(FCFLAGS) $(FLASHFLAGS) $^ -o $@
    
FLASHOBJS = $(FLASHSRCS:.F90=.o)
FOBJS = $(FSRCS:.F90=.o)

$(PROG): $(FLASHOBJS) $(FOBJS)
	$(FCC) $(FCFLAGS) $(FLASHFLAGS) $(FLASHOBJS) $(FOBJS) $(LIBS) -o $(PROG)

LIBS = -L/Users/Shared/hypre-2.13.0/src/hypre/lib -lHYPRE

all: $(PROG)

.PHONY: clean

clean:
	rm -rf *.mod *.o $(PROG)

run: ${PROG} 
	mpirun -np 1 ./${PROG}


