
!!$ Author:
!!$   Yuanqing Wu, KAUST, Saudi Arabia
!!$
!!$ History:
!!$   2015-2-9 by Yuanqing Wu
!!$
!!$ Support:
!!$   wuyuanq@gmail.com

module RST_flashcalculationDriver

    use RST_globalFlashData
    use RST_flashcalculation_fullgrid_2c

contains

    subroutine flashcalculationDriver()

        implicit none
       
        integer, parameter :: GRIDSIZE_P = 257 ! the size of the grid generated by the full grids with TABLESIZE
        integer, parameter :: GRIDSIZE_Z1 = 257
        real(kind=8), parameter :: PMIN = 1.9D6!1.800D6!
        real(kind=8), parameter :: PMAX = 2.1D6!2.300D6!
        real(kind=8), parameter :: PSTEP = (PMAX-PMIN)/(GRIDSIZE_P-1)

        real(kind=8), dimension(:), pointer :: z, xW, xN, v
        real(kind=8) :: xiW, xiN, densiW, densiN, Sw, Cf
        logical :: isW, isN
        integer :: i, j

        open(unit=110, file="dummyfullgrid_2c.txt", status='replace')

        allocate(z(Nc))
        allocate(xW(Nc))
        allocate(xN(Nc))
        allocate(v(Nc))

        allocate(xtable(Nc,TABLESIZE))
        allocate(ytable(Nc,TABLESIZE))
        allocate(xiLtable(TABLESIZE))
        allocate(xiGtable(TABLESIZE))
        allocate(rhoLtable(TABLESIZE))
        allocate(rhoGtable(TABLESIZE))
        allocate(sLtable(TABLESIZE))
        allocate(vtable(Nc,TABLESIZE))
        allocate(Cftable(TABLESIZE))
        allocate(isWtable(TABLESIZE))
        allocate(isNtable(TABLESIZE))

        open(unit=120, file=FULLGRIDPREFIX//"xW1.txt", status='old')
        open(unit=130, file=FULLGRIDPREFIX//"xW2.txt", status='old')
        open(unit=140, file=FULLGRIDPREFIX//"xN1.txt", status='old')
        open(unit=150, file=FULLGRIDPREFIX//"xN2.txt", status='old')
        open(unit=160, file=FULLGRIDPREFIX//"xiW.txt", status='old')
        open(unit=170, file=FULLGRIDPREFIX//"xiN.txt", status='old')
        open(unit=180, file=FULLGRIDPREFIX//"densiW.txt", status='old')
        open(unit=190, file=FULLGRIDPREFIX//"densiN.txt", status='old')
        open(unit=200, file=FULLGRIDPREFIX//"sW.txt", status='old')
        open(unit=210, file=FULLGRIDPREFIX//"v1.txt", status='old')
        open(unit=220, file=FULLGRIDPREFIX//"v2.txt", status='old')
        open(unit=230, file=FULLGRIDPREFIX//"Cf.txt", status='old')
        open(unit=240, file=FULLGRIDPREFIX//"liquid.txt", status='old')
        open(unit=250, file=FULLGRIDPREFIX//"gas.txt", status='old')

        read(120,*) xtable(1,1:TABLESIZE)
        read(130,*) xtable(2,1:TABLESIZE)
        read(140,*) ytable(1,1:TABLESIZE)
        read(150,*) ytable(2,1:TABLESIZE)
        read(160,*) xiLtable(1:TABLESIZE)
        read(170,*) xiGtable(1:TABLESIZE)
        read(180,*) rhoLtable(1:TABLESIZE)
        read(190,*) rhoGtable(1:TABLESIZE)
        read(200,*) sLtable(1:TABLESIZE)
        read(210,*) vtable(1,1:TABLESIZE)
        read(220,*) vtable(2,1:TABLESIZE)
        read(230,*) Cftable(1:TABLESIZE)
        read(240,*) isWtable(1:TABLESIZE)
        read(250,*) isNtable(1:TABLESIZE)

        do i = 0, GRIDSIZE_P-1
            do j = 0, GRIDSIZE_Z1-1

                print *, i, j

                z(1) = j*1.D0/(GRIDSIZE_Z1-1)
                z(2) = 1 - z(1)

                call flashcalculation_fullgrid_2c( PMIN+i*PSTEP, z, xW, xN, xiW, xiN, &!
                    densiW, densiN, Sw, v, Cf, isW, isN )

                write(110, fmt="(es12.5)") PMIN+i*PSTEP, z, xW, xN, xiW, xiN, densiW, densiN, Sw, v, Cf
                write(110, fmt="(L1)") isW, isN

            end do
        end do

        deallocate(z)
        deallocate(xW)
        deallocate(xN)
        deallocate(v)

        close(110)
        close(120)
        close(130)
        close(140)
        close(150)
        close(160)
        close(170)
        close(180)
        close(190)
        close(200)
        close(210)
        close(220)
        close(230)
        close(240)
        close(250)

    end subroutine flashcalculationDriver

end module RST_flashcalculationDriver
